server:
  port: 8084

spring:
  application:
    name: reinput-workspace-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true    
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
